# Generated by Django 3.2 on 2021-12-20 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='second_name',
        ),
    ]
